### ISSUE TITLE
Bug: No validation on 'api/submissions' allows to submit other's answers and get marks. 

### ISSUE THREAD

**Issue by hariwij** [sliit-foss/bashaway-backend#123]
# Description
When a user adds a submission, the file is directly uploaded to the Azure storage bucket. After upload completion, a request is made to `api/submissions` to inform the backend uploaded file URL and the question ID. Since there is no validation done at the backend to check the uploaded file URL belongs to the current user, another user can retrieve a file URL from GitHub Actions logs and submit it. This will trigger answer checking action as usual with the stolen URL and if the victim's submission is successful eventually the malicious user will get the marks.

# Step To Reproduce
1. Open browser Dev tools - network tab.
2. Go to any challenge and submit any zip file. 
3. Now copy the POST request to the `api/submissions` endpoint as CURL.
<img width="661" alt="image" src="https://github.com/user-attachments/assets/6b6d1ff5-9a1c-4607-9d0e-30eb81b63e51">
<img width="524" alt="image" src="https://github.com/user-attachments/assets/d0948ef1-6eb8-4f2f-89e6-03780d042b9a">

5. Now go to the GitHub action page and find a successful submission by another user. 
<img width="673" alt="image" src="https://github.com/user-attachments/assets/34985fc4-73d5-4e2e-b091-3ed19115ee87">
6. Open the action log go to the section 'Download and extract submission files' and copy the file URL.
<img width="1342" alt="image" src="https://github.com/user-attachments/assets/6d890f75-40d3-4787-a1ff-1b742c795de6">
7. Now replace the file URL in the CURL request you copied earlier with a new one and send the request.
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/e0b0531d-7e26-461c-856e-b64705d86fe3">
8. Now wait until the answer-checking action is executed.
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/aafeadca-d3c1-4a86-a37e-85d5815d330f">

# Suggested Fixes
- Make the Team name read-only and add a check to confirm the URL submitted is valid by team name using the current user session.
     - `https://bashawaysolutions.blob.core.windows.net/production/DreamGen/..........` 
 - Modify the bucket path to contain a user ID. And check with the current user session.
     - `https://bashawaysolutions.blob.core.windows.net/production/{user_objectid}/......`
- Use pre-signed URLs with uploading files for submissions. 
     - Genatared URL must be saved in DB before sending it to the front end.
     - After file uploading is completed using a pre-signed URL, another request has to be made to trigger answer checking action.

**Comment by Akalanka47000** [comment]
Closing since the fix is merged. Thanks once again
